import { randomUUID } from "node:crypto";
import Link from "next/link";
import { trainingAction } from "../actions/training";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { isTrainingPackageSelectable, trainingPackageDisplayStatus } from "../lib/package-availability";

function Field({ name, label, type = "text", value, required = true }: { name: string; label: string; type?: string; value?: string | number; required?: boolean }) {
  return <label className="grid gap-1 text-sm">{label}<Input name={name} type={type} defaultValue={value} required={required} /></label>;
}
function Choice({ name, label, options, optional = false }: { name: string; label: string; options: any[]; optional?: boolean }) {
  return <label className="grid gap-1 text-sm">{label}<select className="h-10 rounded border bg-background px-2" name={name} required={!optional}><option value="">{optional ? "None" : "Select"}</option>{options.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>;
}
function Form({ operation, children, member, timeZone }: { operation: string; children: React.ReactNode; member: boolean; timeZone: string }) {
  return <form action={trainingAction} className="grid gap-3 rounded-lg border p-4"><input type="hidden" name="operation" value={operation}/><input type="hidden" name="surface" value={member ? "member" : "operator"}/><input type="hidden" name="timeZone" value={timeZone}/><input type="hidden" name="requestKey" value={randomUUID()}/>{children}<Button type="submit">Save</Button></form>;
}
export function TrainingWorkspace({ data, member = false, error, success }: { data: any; member?: boolean; error?: string; success?: string }) {
  const formProps = { member, timeZone: data.timeZone };
  const now = Number.isSafeInteger(data.asOf) ? data.asOf : Number.NaN;
  const selectablePackages = data.packages.filter((pack: any) => isTrainingPackageSelectable(pack, now));
  const name = (rows: any[], id: string) => rows.find(row => row.id === id)?.name || id;
  const date = (value: string) => new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: data.timeZone }).format(new Date(value));
  return <div className="space-y-6">
    <p className="text-sm text-muted-foreground">Appointments and coaching · times shown in {data.timeZone}. Training packages are purchased through the studio; staff record the settled payment reference. Online package checkout is not available.</p>
    {error && <p role="alert" className="rounded border border-red-500 p-3">{error}</p>}{success && <p role="status">{success}</p>}
    <section className="space-y-3"><h2 className="text-xl font-semibold">Training packages</h2>{data.packages.length === 0 && <p>No recorded packages. Contact the studio to purchase a package.</p>}
      {data.packages.map((pack: any) => <article key={pack.id} className="rounded-lg border p-4 space-y-2"><h3 className="font-semibold">{pack.serviceName} · {pack.durationMinutes} minutes</h3><p>{pack.creditsRemaining}/{pack.totalCredits} credits · {name(data.locations, pack.locationId)} · expires {date(pack.expiresAt)} · {trainingPackageDisplayStatus(pack, now)}</p><p className="text-sm">Cancel before the appointment starts to return its credit to this same package and expiry. Expired credits cannot book later sessions.</p>
        {data.canManageAppointments && pack.status === "active" && <details><summary>Record an externally settled unused-credit refund</summary><Form operation="refund" {...formProps}><input type="hidden" name="packageId" value={pack.id}/><Field name="amount" type="number" label="Settled refund in cents (unused units only)" value={Math.floor(pack.amount * pack.creditsRemaining / pack.totalCredits)}/><Field name="refundReference" label="External settled refund reference"/><p>Complete or cancel every reserved appointment first. This action records evidence and retires the unused credits; it does not send money.</p></Form></details>}
      </article>)}
    </section>
    {(data.memberId || data.canManageAppointments) && <section className="space-y-3"><h2 className="text-xl font-semibold">Reserve personal training</h2><Form operation="book" {...formProps}>
      {data.canManageAppointments ? <Choice name="memberId" label="Member" options={data.members}/> : <input type="hidden" name="memberId" value={data.memberId}/>}
      <Choice name="trainingPackageId" label="Package" options={selectablePackages.map((p: any) => ({ id: p.id, name: `${p.serviceName} · ${p.creditsRemaining} credits · ${p.id}` }))}/>
      <Choice name="instructorId" label="Instructor" options={data.instructors}/><Choice name="locationId" label="Package location" options={data.locations}/><Choice name="resourceId" label="Room or resource" options={data.resources} optional/><Field name="startTime" label={`Start (${data.timeZone})`} type="datetime-local"/><Field name="memberNotes" label="Notes" required={false}/><p className="text-sm">One credit is reserved immediately. The package fixes service, duration, price and location. Availability and conflicts are checked when you save.</p>
    </Form></section>}
    <section className="space-y-3"><h2 className="text-xl font-semibold">Published availability</h2><ul className="space-y-1">{data.availability.map((row: any) => <li key={row.id}>{name(data.instructors, row.instructorId)} · {name(data.locations, row.locationId)} · {row.type === "recurring" ? ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][row.dayOfWeek] : row.date ? date(row.date) : "Undated"} · {row.startTime}–{row.endTime} · {row.isAvailable ? "available" : "unavailable"}</li>)}</ul></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Appointments</h2>{data.appointments.length === 0 && <p>No appointments on this page.</p>}{data.appointments.map((row: any) => <article className="rounded-lg border p-4 space-y-2" key={row.id}><h3 className="font-semibold">{row.serviceName} · {date(row.startTime)}</h3><p>{name(data.instructors, row.instructorId)} · {row.status.replaceAll("_", " ")}</p>{row.cancellationReason && <p>{row.cancellationReason}</p>}
      {["scheduled", "confirmed"].includes(row.status) && (data.canManageAppointments || row.memberId === data.memberId) && <details><summary>Reschedule or change instructor</summary><Form operation="reschedule" {...formProps}><input type="hidden" name="appointmentId" value={row.id}/><Choice name="instructorId" label="Replacement instructor (leave blank to retain)" options={data.instructors} optional/><Field name="startTime" label={`New start (${data.timeZone})`} type="datetime-local"/><Field name="reason" label="Reason"/><p>The old reservation is retained if the replacement cannot be booked.</p></Form></details>}
      {["scheduled", "confirmed", "checked_in"].includes(row.status) && <Form operation="transition" {...formProps}><input type="hidden" name="appointmentId" value={row.id}/><Choice name="status" label="Next state" options={(data.canManageAppointments || data.isInstructor ? ["cancelled", "checked_in", "completed", "no_show"] : ["cancelled"]).map(id => ({ id, name: id.replaceAll("_", " ") }))}/><Field name="reason" label="Reason (required to cancel)" required={false}/></Form>}
    </article>)}</section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Coaching work</h2>{data.assignments.length === 0 && <p>No assigned coaching work.</p>}{data.assignments.map((row: any) => <article className="rounded-lg border p-4 space-y-3" key={row.id}><h3 className="font-semibold">{row.title} · {row.status}</h3><p className="whitespace-pre-wrap">{row.instructions}</p><p>Due {date(row.dueAt)}</p>{row.memberEvidence && <p className="whitespace-pre-wrap">Progress: {row.memberEvidence}</p>}{row.review && <p className="whitespace-pre-wrap">Coach: {row.review}</p>}
      {row.status === "assigned" && row.memberId === data.memberId && <Form operation="progress" {...formProps}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value="submitted"/><Field name="text" label="What you completed, duration and observations"/></Form>}
      {data.canManagePrograms || data.isInstructor ? row.status === "submitted" && <Form operation="progress" {...formProps}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="status" value="reviewed"/><Field name="text" label="Review and next steps"/></Form> : null}
    </article>)}</section>
    {data.canManageAppointments && <section className="space-y-4"><h2 className="text-xl font-semibold">Training setup and sales evidence</h2><details><summary>Record a purchased package</summary><Form operation="package" {...formProps}><Choice name="memberId" label="Member" options={data.members}/><Choice name="locationId" label="Location" options={data.locations}/><Field name="serviceName" label="Purchased service"/><Field name="totalCredits" type="number" label="Purchased credits"/><Field name="durationMinutes" type="number" label="Minutes per appointment" value={60}/><Field name="amount" type="number" label="Settled total in USD cents"/><Field name="purchaseReference" label="External settled payment reference"/><Field name="purchasedAt" type="datetime-local" label="Payment date"/><Field name="expiresAt" type="datetime-local" label="Agreed package expiry"/><p>Verify the external payment is settled and these terms match the member agreement. Never use this form for an unpaid promise.</p></Form></details>
      <details><summary>Publish availability or time off</summary><Form operation="availability" {...formProps}><Field name="id" label="Existing availability ID to amend (optional)" required={false}/><Choice name="instructorId" label="Instructor" options={data.instructors}/><Choice name="locationId" label="Location" options={data.locations}/><Choice name="type" label="Type" options={["recurring", "one_time", "time_off"].map(id => ({id, name:id}))}/><Choice name="dayOfWeek" label="Weekday (recurring only)" options={["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((name,id)=>({id:String(id), name}))} optional/><Field name="date" type="date" label="Date (one time or time off)" required={false}/><Field name="fromTime" type="time" label="From"/><Field name="toTime" type="time" label="To"/><Field name="reason" label="Reason" required={false}/><p>Changes that invalidate already reserved appointments are rejected.</p></Form></details>
    </section>}
    {data.canManagePrograms && <details><summary>Assign coaching work</summary><Form operation="coaching" {...formProps}><Choice name="memberId" label="Member" options={data.members}/><Choice name="instructorId" label="Coach" options={data.instructors}/><Field name="title" label="Goal / session title"/><label>Instructions<textarea className="w-full rounded border bg-background p-2" name="instructions" rows={4} required/></label><Field name="dueAt" type="datetime-local" label="Due"/></Form></details>}
    {data.canManagePeople && <section className="space-y-4"><h2 className="text-xl font-semibold">Inquiry and trial follow-up</h2>{data.leads.map((lead: any) => <article key={lead.id} className="rounded border p-3"><h3>{lead.name} · {lead.email} · {lead.status}</h3><p>Source: {lead.source}; next action {lead.nextActionAt ? date(lead.nextActionAt) : "not scheduled"}</p><details><summary>History</summary>{lead.history.map((entry: any, index: number) => <p key={index}>{entry.at} · {entry.to} · {entry.note}</p>)}</details></article>)}<Form operation="lead" {...formProps}><Field name="name" label="Name"/><Field name="email" type="email" label="Email (matches the existing case when updating)"/><Field name="source" label="Inquiry source" value="operator"/><Choice name="status" label="State" options={["new","contacted","trial_booked","trial_attended","converted","closed"].map(id=>({id,name:id.replaceAll("_"," ")}))}/><Field name="trialAt" type="datetime-local" label="Trial appointment" required={false}/><Field name="nextActionAt" type="datetime-local" label="Next follow-up" required={false}/><Choice name="memberId" label="Matching registered member (conversion only)" options={data.members} optional/><Field name="note" label="Follow-up / transition evidence"/><p>Trial times are follow-up appointments; class capacity still requires a separate class booking. Recording an inquiry does not grant marketing consent.</p></Form></section>}
    <nav aria-label="Training pages" className="flex gap-4">{data.skip > 0 && <Link href={`?skip=${Math.max(0, data.skip - 50)}`}>Previous</Link>}<Link href={`?skip=${data.skip + 50}`}>Next 50 records</Link></nav>
  </div>;
}
