import { randomUUID } from "node:crypto";
import Link from "next/link";
import { requireDashboardUser } from "@/features/dashboard/lib/current-user";
import { PageContainer } from "@/features/dashboard/components/PageContainer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { loadRetailWorkspace, retailAction } from "../actions/retail";
function Field({ name, label, type = "text", value, required = true }: { name: string; label: string; type?: string; value?: string | number; required?: boolean }) { return <label className="grid gap-1">{label}<Input name={name} type={type} defaultValue={value} required={required}/></label>; }
function Form({ operation, children }: { operation: string; children: React.ReactNode }) { return <form action={retailAction} className="grid gap-3 rounded-lg border p-4"><input type="hidden" name="operation" value={operation}/><input type="hidden" name="requestKey" value={randomUUID()}/>{children}<Button type="submit">Record</Button></form>; }
function Site({ locations, includeInactive = false }: { locations: any[]; includeInactive?: boolean }) { return <label>Location<select className="ml-2 rounded border bg-background p-2" name="locationId" required><option value="">Select</option>{locations.filter(row => includeInactive || row.isActive).map(row => <option key={row.id} value={row.id}>{row.name}{row.isActive ? "" : " (inactive)"}</option>)}</select></label>; }
export default async function RetailPage({ searchParams }: { searchParams: Promise<{ skip?: string; error?: string; success?: string }> }) {
  await requireDashboardUser(); const params = await searchParams; const data = await loadRetailWorkspace(Number(params.skip || 0));
  const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value / 100);
  return <PageContainer title="Retail"><div className="space-y-6"><p>Staffed counter sales · USD · cash or externally settled payment. Taxes are not calculated here; enter externally determined gross prices and retain tax evidence with your bookkeeping. This workspace records tender evidence; it does not charge cards or send refunds.</p>{params.error && <p role="alert" className="rounded border border-red-500 p-3">{params.error}</p>}{params.success && <p role="status">{params.success}</p>}
    <section className="space-y-3"><h2 className="text-xl font-semibold">Counter sale</h2><Form operation="sale"><Site locations={data.locations}/><div className="space-y-2">{data.items.filter((row: any) => row.isActive).map((row: any) => <label key={row.id} className="grid grid-cols-[1fr_6rem] gap-2 items-center"><span>{row.name} ({row.sku}) · {money(row.unitAmount)} · {row.stockOnHand} available · {data.locations.find((site: any) => site.id === row.locationId)?.name}</span><input type="hidden" name="itemId" value={row.id}/><Input name="quantity" aria-label={`Quantity of ${row.name}`} type="number" min={0} step={1} defaultValue={0}/></label>)}</div><label>Tender<select className="ml-2 rounded border bg-background p-2" name="tender"><option value="cash">Cash received</option><option value="external">External payment settled</option></select></label><Field name="settledAmount" type="number" label="Sale total received in USD cents (after cash change)"/><Field name="paymentReference" label="External settled payment reference (required for external tender)" required={false}/><label><input name="settled" type="checkbox" value="yes" required/> I received the cash or verified the external settlement for these items.</label><p>Only items at the selected site can be sold together. The server calculates the amount from current catalog prices and rejects insufficient stock.</p></Form></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Sales and returns</h2>{data.sales.map((sale: any) => <article key={sale.id} className="rounded border p-4 space-y-2"><h3 className="font-semibold">{sale.id} · {money(sale.totalAmount)} · {sale.tender}</h3><p>{new Date(sale.soldAt).toISOString()} · {sale.paymentReference || "cash"}</p><ul>{sale.lines.map((line: any) => <li key={line.itemId}>{line.quantity} × {line.name} · {money(line.unitAmount)} each</li>)}</ul><details><summary>Record refund and returned units</summary><Form operation="return"><input type="hidden" name="saleId" value={sale.id}/>{sale.lines.map((line: any) => <div key={line.itemId} className="grid gap-2"><input type="hidden" name="itemId" value={line.itemId}/><Field name="quantity" type="number" label={`Units returned: ${line.name} (${line.quantity} originally sold)`} value={0}/><label><input type="checkbox" name={`restock:${line.itemId}`} value="yes"/> Returned units are resalable; restore stock.</label></div>)}<Field name="reason" label="Return reason"/><Field name="settledRefundAmount" type="number" label="Amount refunded for these units in USD cents"/><Field name="refundReference" label="External settled refund reference (required for external tender)" required={false}/><label><input type="checkbox" name="settled" value="yes" required/> I refunded the original price for these units through the original tender.</label><p>Previously returned units cannot be refunded again. Current catalog price changes do not change the original refund price.</p></Form></details></article>)}{data.returns.map((row: any) => <p key={row.id}>Return {row.id} · sale {row.saleId} · {money(row.refundAmount)} · {row.reason}</p>)}</section>
    <details><summary>Catalog and reasoned stock adjustment</summary><Form operation="item"><Site locations={data.locations}/><Field name="sku" label="SKU (matches an existing item at this site when updating)"/><Field name="name" label="Item name"/><Field name="unitAmount" type="number" label="Gross unit price in USD cents (taxes not calculated)"/><Field name="stockDelta" type="number" label="Signed stock adjustment (+received / -damaged)" value={0}/><Field name="reason" label="Adjustment or price-change reason"/><label>Status<select name="isActive" className="ml-2 rounded border bg-background p-2"><option value="yes">Active</option><option value="no">Archived for future sales</option></select></label></Form></details>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Retail cash drawer close</h2><Form operation="close"><Site locations={data.locations} includeInactive/><Field name="periodStart" type="datetime-local" label="Period start (UTC, inclusive)"/><Field name="periodEnd" type="datetime-local" label="Period end (UTC, exclusive)"/><Field name="openingAmount" type="number" label="Opening cash in USD cents" value={0}/><Field name="countedAmount" type="number" label="Cash counted in USD cents"/><Field name="reason" label="Variance reason and follow-up" required={false}/><p>Expected cash = opening float + recorded cash sales − recorded cash refunds. External card/bank payments require separate statement reconciliation. Closed periods cannot overlap.</p></Form>{data.closes.map((row: any) => <article className="rounded border p-3" key={row.id}><h3>{new Date(row.periodStart).toISOString()} → {new Date(row.periodEnd).toISOString()}</h3><p>Expected {money(row.expectedAmount)} · counted {money(row.countedAmount)} · variance {money(row.varianceAmount)}</p><p>{row.reason}</p></article>)}</section>
    <section className="space-y-2"><h2 className="text-xl font-semibold">Stock evidence</h2>{data.stockEntries.map((row: any) => <p key={row.id}>{new Date(row.createdAt).toISOString()} · {data.items.find((item: any) => item.id === row.itemId)?.sku || row.itemId}: {row.quantity > 0 ? "+" : ""}{row.quantity} → {row.balanceAfter} · {row.reason}</p>)}</section>
    <nav aria-label="Retail history pages" className="flex gap-4">{data.skip > 0 && <Link href={`?skip=${Math.max(0, data.skip - 50)}`}>Previous</Link>}<Link href={`?skip=${data.skip + 50}`}>Next 50 records</Link></nav>
  </div></PageContainer>;
}
